### ISSUE TITLE
Workloads associated with wrong map location (JSON import)

### ISSUE THREAD

**Issue by berstr** [newrelic/nr1-workload-geoops#118]
## Description

When importing a JSON file with 2 locations associated with 2 separate workloads, the association between workload and map location is flipped. 

## Steps to Reproduce

When importing the attached JSON file (see attached ZIP file), to NR1 GeoOps v1.4.3 (currently in the app catalog, 2020-08-12).

You would need to edit the JSON file so it points to workloads you have access to.
Otherwise, I am more than happy to jump on a video call and show it to you in my account.

## Expected Behaviour

Workloads associated with a map location should be displayed once I click on that location within the map.

## Relevant Logs / Console output

None

* NR1 CLI version used: I was using the version from the app catalog (v1.4.3)
* Browser name and version: Chrome Version 84.0.4147.105
* Operating System and version: MacOS 10.14.6

## Additional context

None

[geoops-locations-02.zip](https://github.com/newrelic/nr1-workload-geoops/files/5062079/geoops-locations-02.zip)

**Comment by tangollama** [comment]
@berstr thanks for reporting this. We'll look at it this week.

**Comment by tangollama** [comment]
@berstr can you give this bug another validation go. I suspect some of the refactoring work we shipped in `v. 1.5.1` will address this.

**Comment by berstr** [comment]
@tangollama after using v1.5.1, it all works fine - thanks.
