### ISSUE TITLE
Multiple workloads per location

### ISSUE THREAD

**Issue by Liquidlights** [newrelic/nr1-workload-geoops#119]
[NOTE]: # ( ^^When attempting to add more than one workload to a location getting an "Oops, something went wrong!" message. Or only displays info for one workload^^ )

## Description

[NOTE]: # ( cannot add more than one workload to a location tag. Regardless of how many entities are associated (1 or 100) it still seems to error out. or in the case of workloads with a small amount of entities will only show info for one workload and not the others. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Steps to Reproduce

[NOTE]: # ( Add more than one workload to a location, submit and then view map. )

## Expected Behaviour

[NOTE]: # ( I expect to be able to see all the data associated with multiple workloads per location on GeoOps. )

## Relevant Logs / Console output

[NOTE]: # ( N/A. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* NR1 CLI version used: GeoOps Version 1.4.3 released on July 23, 2020
* Browser name and version: Chrome Version 84.0.4147.125 (Official Build) (64-bit)
* Operating System and version: Microsoft Windows 10.0.2.1000

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by tangollama** [comment]
@Liquidlights thanks for reporting this. We'll look into it.
