### ISSUE TITLE
Entity limit of 124

### ISSUE THREAD

**Issue by amarbarot** [newrelic/nr1-workload-geoops#132]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

GeoOps can only seem to support up to 124 entities, if i increase the entity limit to 125 the map breaks, we need this limit increased to 10,000. 

Below is an example of a map with 4 workloads attached, that have between them 124 entities, the map loads fine and no problems:
<img width="1912" alt="Before" src="https://user-images.githubusercontent.com/53010809/91714685-4545ae80-eb5a-11ea-8820-906841abe4ab.png">

After adding one more entity the form no longer loads:
<img width="1912" alt="After" src="https://user-images.githubusercontent.com/53010809/91714722-4f67ad00-eb5a-11ea-8a63-30260d556ea7.png">

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )

## Expected Behaviour

[NOTE]: # ( Tell us what you expected to happen. )

## Relevant Logs / Console output

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* NR1 CLI version used:
* Browser name and version:
* Operating System and version:

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by tangollama** [comment]
@amarbarot thanks for this issue. I/we'll look into it this week. cc: @ricegi

**Comment by tangollama** [comment]
@amarbarot follow up: your screenshot makes me think that this was run against an older version of the app. As of version 1.5.1, we've made a number of performance improvements, including moving the loading of underlying entities to the Detail screen. I've tested it against some significantly workloads and not generated errors. Could you verify which version of the application you're running. The current New Relic One Catalog version is `Version 1.5.1 released on August 27, 2020`.

**Comment by amarbarot** [comment]
@tangollama ah!, The version I am running is the one we deployed to originally fix the issue in July, i think 1.1.7

![image](https://user-images.githubusercontent.com/53010809/91755333-eeab9500-eb98-11ea-8326-0cf6814cef75.png)

So 1.5.1 fixes this issue, do you know if we have an entity limit with 1.5.1, can it load hundreds/thousands of entities without breaking?

**Comment by amarbarot** [comment]
@tangollama Ive downloaded 1.5.1 and its working a lot better, im going to attach 15 accounts worth of workloads and see how it performs, if we have no issues ill close this ticket.

I'm so happy :), the business value of these tool is very high.

**Comment by amarbarot** [comment]
Ok, GeoOps is performing fine. Im happy and closing the ticket.

**Comment by tangollama** [comment]
Awesome. Thanks @amarbarot.
