### ISSUE TITLE
Map selection view should be scrollable

### ISSUE THREAD

**Issue by AndrewConacher** [newrelic/nr1-workload-geoops#134]
[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

## Summary

The map selection view is not scrollable and requires shrinking the resolution to see more maps. This issue appears when an account has access to a large number of maps.

## Desired Behaviour

Make the pane scrollable so we dont have to manipulate the resolution

## Possible Solution

[NOTE]: # ( Not required. Suggest how to implement the addition or change. )

## Additional context

Two example screenshots provided

[TIP]:  # ( Why does this feature matter to you? What unique circumstances do you have? )
![image](https://user-images.githubusercontent.com/20827050/96144167-987b9100-0f4f-11eb-936c-a337d46fb9dc.png)

![image](https://user-images.githubusercontent.com/20827050/96144196-a4675300-0f4f-11eb-80c8-1dc6c21b40a8.png)

**Comment by danielgolden** [comment]
Thanks for the issue, @AndrewConacher ! I'm going to look into this because I think it's probably an easy fix. I'll follow in this thread when I wrap my mind around the issue and/or solve it. Thanks again!

**Comment by danielgolden** [comment]
@AndrewConacher found [a fix](https://github.com/newrelic/nr1-workload-geoops/pull/135) for this issue. Once it's review we'll get it pushed out to the latest version of the app.

**Comment by tangollama** [comment]
@AndrewConacher thanks for reporting this bug. This should be resolved in the New Relic One Catalog version of the app (v. 1.5.3).

**Comment by AndrewConacher** [comment]
Thanks JoelSent from my Samsung Galaxy smartphone.
-------- Original message --------From: Joel Worrall <notifications@github.com> Date: 4/11/20  6:20 am  (GMT+10:00) To: newrelic/nr1-workload-geoops <nr1-workload-geoops@noreply.github.com> Cc: AndrewConacher <aconacher@newrelic.com>, Mention <mention@noreply.github.com> Subject: Re: [newrelic/nr1-workload-geoops] Map selection view should be scrollable (#134) 
@AndrewConacher thanks for reporting this bug. This should be resolved in the New Relic One Catalog version of the app (v. 1.5.3).

**Comment by AndrewConacher** [comment]
Thanks for getting this fix in. GREATLY appreciated
