### ISSUE TITLE
Fix vulnerability in Geo Ops App

### ISSUE THREAD

**Issue by jpvajda** [newrelic/nr1-workload-geoops#150]
See  JIRA ISSUE `InfoSec-3208` for details.

**Comment by rudouglas** [comment]
@jpvajda added a fix so we check if the Runbook URL is safe before rendering the link. It won't render the button if it fails the check:

<img width="357" alt="Screenshot 2021-05-05 at 11 50 08" src="https://user-images.githubusercontent.com/17122543/117131273-2490c100-ad99-11eb-8156-a7e2226be683.png">
