### ISSUE TITLE
refactor(MapItem): render single map tile instead of whole map

### ISSUE THREAD

**Issue by devfreddy** [newrelic/nr1-workload-geoops#40]
## Summary

Currently the `<MapItem>` component renders an entire map (`<GeoMap>`) in order to show the center point tile for the map. We can reduce the complexity and increase performance here because all we care about is the tile at the given zoom + center point for the map.

## Desired Behaviour

Render/show us just a single map tile not an entire leaflet map via `<GeoMap>`

## Possible Solution

We researched and wrote a function to determine this for a given zoom + lat/lng combo, it's in `shared/utils`.

```js
import { latLngToTile } from '../shared/utils';

const { s, x, y, z } = latLngToTile({
  latLng: [map.lat, map.lng],
  zoom: 10 // TO DO - update to the default zoom the user sets?
});

const url = `https://${s}.tile.openstreetmap.org/${z}/${x}/${y}.png`;
console.log(url);
```

## Additional context

Adding/documenting this to the backlog as we close out the initial milestone and do some cleanup. It's not as big a concern until we run into a use-case with dozens/hundreds of maps coming back in the MapList. Additionally, it should be a pretty easy task for a first time contributor.

**Comment by madecki** [comment]
Started work on it

**Comment by madecki** [comment]
This solution is unfortunately burdened with few issues mentioned on Slack and Meet but I'm listing them here:
- sometimes leaflet endpoints we're returning 404 and that would lead into the need of adding a lot of new logics (i.e. mentioned HoC with validation)
- tiles even when loaded, based on official lat/long -> x/y calculations is pointing into incorrect tiles
- tiles are much lower quality than the map that we're using now

**Comment by madecki** [comment]
Because of inconsistency, poor quality and small preciseness of tiles, we're dropping this idea for now.
