### ISSUE TITLE
Bug: View Map select "Other Maps"

### ISSUE THREAD

**Issue by devfreddy** [newrelic/nr1-workload-geoops#45]
## Description

When viewing a specific map you have a dropdown option for "Other Maps" allowing you to quickly toggle between maps.

However, when selecting a new map, the MapLocation markers don't update/rerender. I suspect we didn't notice this until we had datasets that weren't all the same.

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )

## Expected Behaviour

[NOTE]: # ( Tell us what you expected to happen. )

## Relevant Logs / Console output

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* NR1 CLI version used:
* Browser name and version:
* Operating System and version:

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by madecki** [comment]
Taking this one

**Comment by madecki** [comment]
I wasn't able to reproduce this issue. I couldn't also find "Other Maps" button, there's only "View All Maps".

1. I've created new map and switched to existing - markers have updated
2. I've opened previously created, existing map and switched to another - markers have updated
3. I've returned to previous map again and markers have updated again

I've seen this "Other Maps" in documentation.md file only, "Other Maps" doesn't appear to be used anymore. Please let me know if I missed something @devfreddy , @tangollama

**Comment by tangollama** [comment]
No longer relevant.
