### ISSUE TITLE
feat: map data polling and refreshing

### ISSUE THREAD

**Issue by devfreddy** [newrelic/nr1-workload-geoops#46]
When viewing a specific map, we need a mechanism, from both a UI and functional perspective for when and how frequently we are updating data for the MapLocation's.

A portion of this refresh/polling should be there already as a result of utilizing the underlying SDK components, but we need to ensure its playing well with our custom data fetching components.

**Comment by tangollama** [comment]
Let's go with a 15 second interval. If I've navigated away from the screen, ignore the refresh.
