### ISSUE TITLE
JS Error when adding a Workload that contains Entities outside of the application scope

### ISSUE THREAD

**Issue by tangollama** [newrelic/nr1-workload-geoops#59]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

When including a Workload that contains entities that are outside of the application scope, the `MapLocationDistiller.entityReducer` throws a JS error, trying to read the `guid` from a null object.

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Steps to Reproduce

- Create a workload in a subaccount
- Add an entity from a parent account to that workload
- Enable the Workload GeoOps app for the subaccount only
- Create a new Map and Location
- Add the workload to that Location
- Try to access the Map
- Result: JS Error `Skull & Bones`

[NOTE]: # ( Please be as specific as possible. )

## Expected Behaviour

View the map and workload but without the Entity that is out of scope for that app

[NOTE]: # ( Tell us what you expected to happen. )

## Relevant Logs / Console output

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* NR1 CLI version used:
* Browser name and version:
* Operating System and version:

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by madecki** [comment]
Starting work on it

**Comment by tangollama** [comment]
Unable to reproduce. I suspect we addressed this on fixes @devfreddy recently implemented. Closing.
