### ISSUE TITLE
GeoOps Issues with Large Workloads

### ISSUE THREAD

**Issue by amarbarot** [newrelic/nr1-workload-geoops#77]
I have been testing GeoOps and I love it, but i have a problem with GeoOps maps not loading when i use workloads which have more entities, I have 4 screenshots showing the problem.

Essentially, I create a map, assign a workload which only has one entity and it works fine. As soon as i assigned a larger workload GeoOps breaks on me.

Assigning test workload with one host
![image](https://user-images.githubusercontent.com/53010809/84083859-6a3de180-a9b0-11ea-9d8a-368dfd28c659.png)

![image](https://user-images.githubusercontent.com/53010809/84083900-7f1a7500-a9b0-11ea-9072-7eb01f1ca190.png)

If I edit this small workload, with one that has more entities:
![image](https://user-images.githubusercontent.com/53010809/84084002-a6714200-a9b0-11ea-8d99-643264738547.png)

And i try and reload the map it breaks
![image](https://user-images.githubusercontent.com/53010809/84085537-cbb37f80-a9b3-11ea-932a-8d141cb07262.png)

If i assign the larger workload when building the map, it won't load when i click view map. This only seems to work with tiny workloads.

**Comment by tangollama** [comment]
@amarbarot thanks for the detailed issue. We're prioritizing this work to be addressed soon.

**Comment by amarbarot** [comment]
Thanks @tangollama 

I've been trying different combination of workloads, can't really pinpoint what the tipping point is, a workload with 100 hosts seems to work, anything above 250 breaks it.

Must be a limit somewhere stopping large workloads from loading.

**Comment by amarbarot** [comment]
@tangollama Any news on any progress or when this will be looking into?, I want us to start using it for production monitoring.

**Comment by madecki** [comment]
@amarbarot Hi, I'm putting my hands on this issue now and will try to return with some solution ASAP :)

**Comment by amarbarot** [comment]
Thanks @madecki 

Hopefully you are seeing the same issue on your side also.

The idea is we want a workload per state, each workload will have at-least 1000 entities. We need the dashboard to long

**Comment by tangollama** [comment]
Design/issue notes:

1. It appears that we're running into the documented limit on the number of entities in an `actor.entities(guid)` nerdgraph request,
2. So, we need to chunk the request in 25-entity pages,
3. And deal with the result on the back end

**Steps**
1. Turn this const into a function that generates multiple entities with aliases. I recommend `query1: entities...`, `query2: entities` for each 25-entity "page" https://github.com/newrelic/nr1-workload-geoops/blob/master/nerdlets/shared/services/queries.js#L141
2. In here (https://github.com/newrelic/nr1-workload-geoops/blob/master/nerdlets/shared/components/AlertableEntitiesByGuidsQuery.js#L139) recombinate the results based on the convention of how you've had to chunk the data.

cc: @devfreddy @madecki

**Comment by amarbarot** [comment]
So do i need to download this again and try again?
